spring.application.name=STUDENT
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://dpg-d77smqkhg0os73cfv86g-a.oregon-postgres.render.com:5432/student_yalx
spring.datasource.username=student_yalx_user
spring.datasource.password=v12b9K1BgGMUD7nfNTn25ZkSkSXWBMWH

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect